### ISSUE TITLE
Merge in docker branch on the quickstart project and update quickstart-docker to reflect this

### ISSUE THREAD

**Issue by kazaamjt** [inmanta/quickstart#5]
Currently we still have 2 separate branches, `master` and `docker`, we should clean this up by merging the docker branch into master and as well as update the quickstart-docker readme.

**Comment by wouterdb** [comment]
This may already be resolved?

**Comment by kazaamjt** [comment]
The merge yes, I updated the docs of the quickstart and I'll remove the docker branch
